"""outfit_source

Revision ID: 5f01ad15974e
Revises: d2e8f1a4b9c3
Create Date: 2026-05-12 17:05:42.001468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f01ad15974e'
down_revision: Union[str, Sequence[str], None] = 'd2e8f1a4b9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('source', sa.String(), server_default=sa.text("'manual'"), nullable=False))
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trips', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('outfits', 'source')
    # ### end Alembic commands ###
