"""add_outfit_collections

Revision ID: 60dd2477ee4d
Revises: e1f4b2c8a9d0
Create Date: 2026-04-26 19:37:35.130853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dd2477ee4d'
down_revision: Union[str, Sequence[str], None] = 'e1f4b2c8a9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outfit_collections_id'), 'outfit_collections', ['id'], unique=False)
    op.create_index(op.f('ix_outfit_collections_user_id'), 'outfit_collections', ['user_id'], unique=False)
    op.create_table('outfit_collection_outfits',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['outfit_collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'outfit_id')
    )
    op.drop_index(op.f('ix_items_dominant_color'), table_name='items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_items_dominant_color'), 'items', [sa.literal_column("((color_tags -> 'dominant'::text) ->> 0)")], unique=False)
    op.drop_table('outfit_collection_outfits')
    op.drop_index(op.f('ix_outfit_collections_user_id'), table_name='outfit_collections')
    op.drop_index(op.f('ix_outfit_collections_id'), table_name='outfit_collections')
    op.drop_table('outfit_collections')
    # ### end Alembic commands ###
