"""rm style

Revision ID: adbedd8d6352
Revises: c6d3cf36ae3a
Create Date: 2025-12-22 18:04:45.495824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbedd8d6352'
down_revision: Union[str, Sequence[str], None] = 'c6d3cf36ae3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wardrobe_items', 'style')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wardrobe_items', sa.Column('style', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
